var pokemonList = [
{name: "Bulbasaur", type: "grass"},
{name: "Ivysaur", type: "grass"},
{name: "Venusaur", type: "grass"},
{name: "Charmander", type: "fire"},
{name: "Charmeleon", type: "fire"},
{name: "Charizard", type: "fire"},
{name: "Squirtle", type: "water"},
{name: "Wartortle", type: "water"},
{name: "Blastoise", type: "water"},
{name: "Caterpie", type: "grass"},
{name: "Metapod", type: "grass"},
{name: "Butterfree", type: "grass"},
{name: "Weedle", type: "grass"},
{name: "Kakuna", type: "grass"},
{name: "Beedrill", type: "grass", flying: true},
{name: "Pidgey", type: "normal", flying: true},
{name: "Pidgeotto", type: "normal", flying: true},
{name: "Pidgeot", type: "normal", flying: true},
{name: "Rattata", type: "normal"},
{name: "Raticate", type: "normal"},
];